name: Test Backend

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: |
          pip install fastapi uvicorn pytest

      - name: Run tests
        run: pytest
